version: '2'
services:
  crud-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/crud/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=crud
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
